Exclude AWS SDK components
Otherwise these are conflicting with components elsewhere in Spark and
leading to issues like:

```
java.lang.NoSuchMethodError: 'com.amazonaws.thirdparty.apache.http.client.methods.HttpRequestBase com.amazonaws.http.HttpResponse.getHttpRequest()'
```

seen here:

https://github.com/tadodotcom/data-science-utils/actions/runs/7722511503/job/21050804210?pr=414#step:12:155

Chances are this has only shown up because the loading order of classes
changed with a slightly different version of java.